checkbox_config.settings_form:
  path: '/admin/config/system/checkbox-config'
  defaults:
    _title: 'checkbox config settings'
    _form: 'Drupal\checkbox_config\Form\SettingsForm'
  requirements:
    _permission: 'administer checkbox_config configuration'
