# Schema for the configuration files of the checkbox config module.
checkbox_config.settings:
  type: config_object
  label: 'checkbox config settings'
  mapping:
    example:
      type: string
      label: 'Example'
