<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */

function custom_new_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_mail module.
    case 'help.page.custom_mail':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('How to send an email programmatically') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_mail().
 */
function custom_new_mail($key, &$message, $params) {
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
  $options = [
    'langcode' => $message['langcode'],
  ];

  switch ($key) {
    case 'create_article':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['text'];
      break;
  }
}

/**
 * Implements hook_entity_insert().
 */
function custom_new_entity_insert(EntityInterface $entity) {

  if ($entity->getEntityTypeId() !== 'node' || ($entity->getEntityTypeId() === 'node' && $entity->bundle() !== 'article')) {
    return;
  }

  $mailManager = \Drupal::service('plugin.manager.mail');

  $module = 'custom_new';
  $key = 'create_article';
  $to = \Drupal::currentUser()->getEmail();

  $helptext = \Drupal::configFactory()->getEditable("custom_new.settings")->get("subject");
  $message = \Drupal::configFactory()->getEditable("custom_new.settings")->get("text");
  $token_service = \Drupal::token();
  $hlptxt = $token_service->replace($helptext, ['node'=>$entity], ['clear'=>TRUE]);
  $msg = $token_service->replace($message, ['node'=>$entity], ['clear'=>TRUE]);
  $params['subject'] = $hlptxt;
  $params['text'] = $msg;
  $langcode = \Drupal::currentUser()->getPreferredLangcode();
  $send = TRUE;

  $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
  if ($result['result'] !== TRUE) {

    \Drupal::messenger()->addMessage(t('There was a problem sending your message and it was not sent'), 'error');
  }
  else {

    \Drupal::messenger()->addMessage(t('Your message has been sent.'), 'status');
  }

}

// function custom_new_mail_alter(&$message) {
//   $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
// }
